name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml' # not sure if next line captures this
      - '**/Cargo.toml'
      - '**.rs'
      - '**.java'
  pull_request:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
      - '**.rs'
      - '**.java'
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: moonrepo/setup-rust@v0
        with:
          channel: nightly
          components: rustfmt, clippy

      - name: Check rustfmt
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs:
      - checks
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          components: llvm-tools-preview
          bins: cargo-llvm-cov

      - name: Collect coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

      - uses: codecov/codecov-action@v3
        with:
          files: codecov.json
          fail_ci_if_error: true

  test:
    name: Test (${{ matrix.os.name }}, rust ${{ matrix.rust.name }}, java ${{ matrix.java }})
    needs:
      - checks
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: win, version: windows-latest }
          - { name: linux, version: ubuntu-latest }
        rust:
          - { name: MSRV, version: 1.66.1 }
          - { name: stable, version: stable }
          - { name: nightly, version: nightly }
        java:
          - 8
          - 11
          - 17
    runs-on: ${{ matrix.os.version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - uses: moonrepo/setup-rust@v0
        with:
          channel: ${{ matrix.rust.version }}

      - name: Build
        run: cargo build --all-features --all-targets

      - name: Doctests
        run: cargo test --all-features --doc
        timeout-minutes: 5

      - name: Test
        run: cargo test --all-features --all-targets
        timeout-minutes: 5
